[dev]
   command = "npm run dev"
[build]
  command = "npm run generate"
  publish = "dist"
  functions = 'functions'
[[redirects]]
   from= "/functions/*"
   to = "/.netlify/functions/:splat"
   status = 200

[[redirects]]
  from = "/*"
  to = "/error"
  status = 404